extends SceneTree

## Verifies the godobuf-generated protobuf bindings against golden frames
## encoded by the validator's TS encoder (protobufjs): decode each frame,
## assert the decoded values, re-encode, and require byte-identical output.
## Golden fixture: tests/golden/hermes_proto_golden.json, generated by
## validator/src/validator/tools/generate-hermes-golden.ts — never hand-write.
##   godot --headless --path . --script res://tools/verify_hermes_proto.gd

const HermesPb := preload("res://net/proto/hermes_envelope_pb.gd")
const ValidatorPb := preload("res://net/proto/validator_pb.gd")

var _failures: Array[String] = []


func _initialize() -> void:
	var f := FileAccess.open("res://tests/golden/hermes_proto_golden.json", FileAccess.READ)
	if f == null:
		print("VERIFY hermes_proto: FAIL (missing golden fixture)")
		quit(1)
		return
	var golden: Dictionary = JSON.parse_string(f.get_as_text())
	var cases: Dictionary = golden["cases"]

	_check_client_init(cases["client_init"])
	_check_validate_mismatch(cases["server_validate_mismatch"])
	_check_complete_maps(cases["server_complete_maps"])
	_check_error(cases["server_error"])

	if _failures.is_empty():
		print("VERIFY hermes_proto: PASS (%d cases)" % cases.size())
		quit(0)
	else:
		for m in _failures:
			print("  FAIL: " + m)
		print("VERIFY hermes_proto: FAIL (%d/%d)" % [_failures.size(), cases.size()])
		quit(1)


func _hex_to_bytes(s: String) -> PackedByteArray:
	var out := PackedByteArray()
	for i in range(0, s.length(), 2):
		out.append(("0x" + s.substr(i, 2)).hex_to_int())
	return out


func _expect(cond: bool, msg: String) -> void:
	if not cond:
		_failures.append(msg)


func _roundtrip(name: String, original: PackedByteArray, reencoded: PackedByteArray) -> void:
	_expect(reencoded == original, "%s: re-encode differs (%d vs %d bytes)" % [name, reencoded.size(), original.size()])


func _check_client_init(c: Dictionary) -> void:
	var bytes := _hex_to_bytes(c["bytes"])
	var cm := HermesPb.ClientMessage.new()
	_expect(cm.from_bytes(bytes) == HermesPb.PB_ERR.NO_ERRORS, "client_init: decode failed")
	_expect(cm.get_mid() == "g-1", "client_init: mid")
	_expect(cm.get_message_type() == HermesPb.MessageType.SNAP_API_PROXY, "client_init: message_type")
	var req = cm.get_snap_api_request()
	_expect(req.get_api_method().ends_with("/InitMatch"), "client_init: api_method")
	var init := ValidatorPb.InitMatchRequest.new()
	_expect(init.from_bytes(req.get_payload()) == ValidatorPb.PB_ERR.NO_ERRORS, "client_init: payload decode")
	var pe: Dictionary = c["payload_expect"]
	_expect(init.get_match_id() == pe["match_id"], "client_init: match_id")
	_expect(init.get_player_id() == pe["player_id"], "client_init: player_id")
	_expect(init.get_mode() == pe["mode"], "client_init: mode")
	_expect(init.get_starting_state_json() == pe["starting_state_json"], "client_init: unicode state json")
	_roundtrip("client_init", bytes, cm.to_bytes())


func _check_validate_mismatch(c: Dictionary) -> void:
	var bytes := _hex_to_bytes(c["bytes"])
	var sm := HermesPb.ServerMessage.new()
	_expect(sm.from_bytes(bytes) == HermesPb.PB_ERR.NO_ERRORS, "validate_mismatch: decode failed")
	_expect(sm.get_msg_case() == 50, "validate_mismatch: oneof case")
	var val := ValidatorPb.ValidateActionResponse.new()
	_expect(val.from_bytes(sm.get_api_response().get_payload()) == ValidatorPb.PB_ERR.NO_ERRORS, "validate_mismatch: payload decode")
	var pe: Dictionary = c["payload_expect"]
	_expect(val.get_index() == int(pe["index"]), "validate_mismatch: index")
	_expect(val.get_matched() == pe["matched"], "validate_mismatch: matched")
	_expect(val.get_state_json() == pe["state_json"], "validate_mismatch: state_json")
	_expect(val.get_signature().length() == 64, "validate_mismatch: signature")
	_roundtrip("validate_mismatch", bytes, sm.to_bytes())


func _check_complete_maps(c: Dictionary) -> void:
	var bytes := _hex_to_bytes(c["bytes"])
	var sm := HermesPb.ServerMessage.new()
	_expect(sm.from_bytes(bytes) == HermesPb.PB_ERR.NO_ERRORS, "complete_maps: decode failed")
	var done := ValidatorPb.CompleteMatchResponse.new()
	_expect(done.from_bytes(sm.get_api_response().get_payload()) == ValidatorPb.PB_ERR.NO_ERRORS, "complete_maps: payload decode")
	var pe: Dictionary = c["payload_expect"]
	_expect(done.get_match_id() == pe["match_id"], "complete_maps: match_id")
	var rewards: Dictionary = done.get_rewards()
	_expect(rewards == pe["rewards"], "complete_maps: rewards map %s" % JSON.stringify(rewards))
	var balances: Dictionary = done.get_balances()
	_expect(balances == pe["balances"], "complete_maps: int64-as-string balance %s" % JSON.stringify(balances))
	_expect(done.get_granted() == pe["granted"], "complete_maps: granted")
	_roundtrip("complete_maps", bytes, sm.to_bytes())


func _check_error(c: Dictionary) -> void:
	var bytes := _hex_to_bytes(c["bytes"])
	var sm := HermesPb.ServerMessage.new()
	_expect(sm.from_bytes(bytes) == HermesPb.PB_ERR.NO_ERRORS, "error: decode failed")
	_expect(sm.get_mid() == "g-4", "error: mid")
	_expect(sm.get_msg_case() == 11, "error: oneof case")
	var ee: Dictionary = c["error_expect"]
	_expect(sm.get_error().get_code() == int(ee["code"]), "error: out-of-enum code 500")
	_expect(sm.get_error().get_error_message() == ee["error_message"], "error: message")
	_roundtrip("error", bytes, sm.to_bytes())
