// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: leaderboards_services.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LeaderboardsService_GetScoresDeprecated_FullMethodName             = "/leaderboards.LeaderboardsService/GetScoresDeprecated"
	LeaderboardsService_SetScoreDeprecated_FullMethodName              = "/leaderboards.LeaderboardsService/SetScoreDeprecated"
	LeaderboardsService_IncrementScoreDeprecated_FullMethodName        = "/leaderboards.LeaderboardsService/IncrementScoreDeprecated"
	LeaderboardsService_BatchIncrementScoreDeprecated_FullMethodName   = "/leaderboards.LeaderboardsService/BatchIncrementScoreDeprecated"
	LeaderboardsService_BatchSetScoreDeprecated_FullMethodName         = "/leaderboards.LeaderboardsService/BatchSetScoreDeprecated"
	LeaderboardsService_BatchGetScoresDeprecated_FullMethodName        = "/leaderboards.LeaderboardsService/BatchGetScoresDeprecated"
	LeaderboardsService_GetLeaderboardsDeprecated_FullMethodName       = "/leaderboards.LeaderboardsService/GetLeaderboardsDeprecated"
	LeaderboardsService_CreateLeaderboardDeprecated_FullMethodName     = "/leaderboards.LeaderboardsService/CreateLeaderboardDeprecated"
	LeaderboardsService_DeleteLeaderboardDeprecated_FullMethodName     = "/leaderboards.LeaderboardsService/DeleteLeaderboardDeprecated"
	LeaderboardsService_GetScores_FullMethodName                       = "/leaderboards.LeaderboardsService/GetScores"
	LeaderboardsService_SetScore_FullMethodName                        = "/leaderboards.LeaderboardsService/SetScore"
	LeaderboardsService_IncrementScore_FullMethodName                  = "/leaderboards.LeaderboardsService/IncrementScore"
	LeaderboardsService_BatchIncrementScore_FullMethodName             = "/leaderboards.LeaderboardsService/BatchIncrementScore"
	LeaderboardsService_BatchSetScore_FullMethodName                   = "/leaderboards.LeaderboardsService/BatchSetScore"
	LeaderboardsService_BatchGetScores_FullMethodName                  = "/leaderboards.LeaderboardsService/BatchGetScores"
	LeaderboardsService_GetLeaderboards_FullMethodName                 = "/leaderboards.LeaderboardsService/GetLeaderboards"
	LeaderboardsService_GetTieredLeaderboardDiagnostics_FullMethodName = "/leaderboards.LeaderboardsService/GetTieredLeaderboardDiagnostics"
	LeaderboardsService_GetUserData_FullMethodName                     = "/leaderboards.LeaderboardsService/GetUserData"
	LeaderboardsService_DeleteUserData_FullMethodName                  = "/leaderboards.LeaderboardsService/DeleteUserData"
	LeaderboardsService_CreateLeaderboard_FullMethodName               = "/leaderboards.LeaderboardsService/CreateLeaderboard"
	LeaderboardsService_UpdateLeaderboard_FullMethodName               = "/leaderboards.LeaderboardsService/UpdateLeaderboard"
	LeaderboardsService_PatchLeaderboard_FullMethodName                = "/leaderboards.LeaderboardsService/PatchLeaderboard"
	LeaderboardsService_DeleteLeaderboard_FullMethodName               = "/leaderboards.LeaderboardsService/DeleteLeaderboard"
	LeaderboardsService_CleanupLeaderboard_FullMethodName              = "/leaderboards.LeaderboardsService/CleanupLeaderboard"
	LeaderboardsService_ExportSettings_FullMethodName                  = "/leaderboards.LeaderboardsService/ExportSettings"
	LeaderboardsService_ImportSettings_FullMethodName                  = "/leaderboards.LeaderboardsService/ImportSettings"
	LeaderboardsService_ValidateImportSettings_FullMethodName          = "/leaderboards.LeaderboardsService/ValidateImportSettings"
)

// LeaderboardsServiceClient is the client API for LeaderboardsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LeaderboardsServiceClient interface {
	GetScoresDeprecated(ctx context.Context, in *GetScoresRequest, opts ...grpc.CallOption) (*GetScoresResponse, error)
	SetScoreDeprecated(ctx context.Context, in *SetScoreRequest, opts ...grpc.CallOption) (*SetScoreResponse, error)
	IncrementScoreDeprecated(ctx context.Context, in *IncrementScoreRequest, opts ...grpc.CallOption) (*IncrementScoreResponse, error)
	BatchIncrementScoreDeprecated(ctx context.Context, in *BatchIncrementScoreRequest, opts ...grpc.CallOption) (*BatchIncrementScoreResponse, error)
	BatchSetScoreDeprecated(ctx context.Context, in *BatchSetScoreRequest, opts ...grpc.CallOption) (*BatchSetScoreResponse, error)
	BatchGetScoresDeprecated(ctx context.Context, in *BatchGetScoresRequest, opts ...grpc.CallOption) (*BatchGetScoresResponse, error)
	GetLeaderboardsDeprecated(ctx context.Context, in *GetLeaderboardsRequest, opts ...grpc.CallOption) (*GetLeaderboardsResponse, error)
	CreateLeaderboardDeprecated(ctx context.Context, in *CreateLeaderboardRequest, opts ...grpc.CallOption) (*CreateLeaderboardResponse, error)
	DeleteLeaderboardDeprecated(ctx context.Context, in *DeleteLeaderboardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// GetScores
	// GetScores
	//
	// GetScores gets the standings within a leaderboard
	GetScores(ctx context.Context, in *GetScoresRequest, opts ...grpc.CallOption) (*GetScoresResponse, error)
	// SetScore
	//
	// SetScore updates the score on the leaderboard for the logged in user (if applicable)
	SetScore(ctx context.Context, in *SetScoreRequest, opts ...grpc.CallOption) (*SetScoreResponse, error)
	// IncrementScore
	//
	// IncrementScore increments the score on the leaderboard for the logged in user
	IncrementScore(ctx context.Context, in *IncrementScoreRequest, opts ...grpc.CallOption) (*IncrementScoreResponse, error)
	// BatchIncrementScore
	//
	// BatchIncrementScore increments the score on the leaderboard for the logged in user
	BatchIncrementScore(ctx context.Context, in *BatchIncrementScoreRequest, opts ...grpc.CallOption) (*BatchIncrementScoreResponse, error)
	// BatchSetScore
	//
	// BatchSetScore updates the score on the leaderboard for the logged in user (if applicable)
	BatchSetScore(ctx context.Context, in *BatchSetScoreRequest, opts ...grpc.CallOption) (*BatchSetScoreResponse, error)
	// BatchGetScore
	//
	// BatchGetScore gets the standings within a leaderboard
	BatchGetScores(ctx context.Context, in *BatchGetScoresRequest, opts ...grpc.CallOption) (*BatchGetScoresResponse, error)
	// GetLeaderboards
	//
	// GetLeaderboards returns all the leaderboards within the cluster
	GetLeaderboards(ctx context.Context, in *GetLeaderboardsRequest, opts ...grpc.CallOption) (*GetLeaderboardsResponse, error)
	GetTieredLeaderboardDiagnostics(ctx context.Context, in *GetTieredLeaderboardDiagnosticsRequest, opts ...grpc.CallOption) (*TieredLeaderboardInfo, error)
	// GetUserData
	//
	// GetUserData returns all the leaderboards data for user within the cluster
	GetUserData(ctx context.Context, in *GetUserDataRequest, opts ...grpc.CallOption) (*GetUserDataResponse, error)
	// DeleteUserData
	//
	// DeleteUserData deletes the leaderboard data for user
	DeleteUserData(ctx context.Context, in *DeleteUserDataRequest, opts ...grpc.CallOption) (*DeleteUserDataResponse, error)
	// CreateLeaderboard
	//
	// CreateLeaderboard creates a new leaderboard with the given settings
	CreateLeaderboard(ctx context.Context, in *CreateLeaderboardRequest, opts ...grpc.CallOption) (*CreateLeaderboardResponse, error)
	UpdateLeaderboard(ctx context.Context, in *UpdateLeaderboardRequest, opts ...grpc.CallOption) (*UpdateLeaderboardResponse, error)
	PatchLeaderboard(ctx context.Context, in *PatchLeaderboardRequest, opts ...grpc.CallOption) (*PatchLeaderboardResponse, error)
	DeleteLeaderboard(ctx context.Context, in *DeleteLeaderboardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CleanupLeaderboard(ctx context.Context, in *CleanupLeaderboardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ExportSettings(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SettingsImportExportData, error)
	ImportSettings(ctx context.Context, in *SettingsImportExportData, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ValidateImportSettings(ctx context.Context, in *SettingsImportExportData, opts ...grpc.CallOption) (*SettingsImportExportData, error)
}

type leaderboardsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLeaderboardsServiceClient(cc grpc.ClientConnInterface) LeaderboardsServiceClient {
	return &leaderboardsServiceClient{cc}
}

func (c *leaderboardsServiceClient) GetScoresDeprecated(ctx context.Context, in *GetScoresRequest, opts ...grpc.CallOption) (*GetScoresResponse, error) {
	out := new(GetScoresResponse)
	err := c.cc.Invoke(ctx, LeaderboardsService_GetScoresDeprecated_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) SetScoreDeprecated(ctx context.Context, in *SetScoreRequest, opts ...grpc.CallOption) (*SetScoreResponse, error) {
	out := new(SetScoreResponse)
	err := c.cc.Invoke(ctx, LeaderboardsService_SetScoreDeprecated_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) IncrementScoreDeprecated(ctx context.Context, in *IncrementScoreRequest, opts ...grpc.CallOption) (*IncrementScoreResponse, error) {
	out := new(IncrementScoreResponse)
	err := c.cc.Invoke(ctx, LeaderboardsService_IncrementScoreDeprecated_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) BatchIncrementScoreDeprecated(ctx context.Context, in *BatchIncrementScoreRequest, opts ...grpc.CallOption) (*BatchIncrementScoreResponse, error) {
	out := new(BatchIncrementScoreResponse)
	err := c.cc.Invoke(ctx, LeaderboardsService_BatchIncrementScoreDeprecated_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) BatchSetScoreDeprecated(ctx context.Context, in *BatchSetScoreRequest, opts ...grpc.CallOption) (*BatchSetScoreResponse, error) {
	out := new(BatchSetScoreResponse)
	err := c.cc.Invoke(ctx, LeaderboardsService_BatchSetScoreDeprecated_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) BatchGetScoresDeprecated(ctx context.Context, in *BatchGetScoresRequest, opts ...grpc.CallOption) (*BatchGetScoresResponse, error) {
	out := new(BatchGetScoresResponse)
	err := c.cc.Invoke(ctx, LeaderboardsService_BatchGetScoresDeprecated_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) GetLeaderboardsDeprecated(ctx context.Context, in *GetLeaderboardsRequest, opts ...grpc.CallOption) (*GetLeaderboardsResponse, error) {
	out := new(GetLeaderboardsResponse)
	err := c.cc.Invoke(ctx, LeaderboardsService_GetLeaderboardsDeprecated_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) CreateLeaderboardDeprecated(ctx context.Context, in *CreateLeaderboardRequest, opts ...grpc.CallOption) (*CreateLeaderboardResponse, error) {
	out := new(CreateLeaderboardResponse)
	err := c.cc.Invoke(ctx, LeaderboardsService_CreateLeaderboardDeprecated_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) DeleteLeaderboardDeprecated(ctx context.Context, in *DeleteLeaderboardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LeaderboardsService_DeleteLeaderboardDeprecated_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) GetScores(ctx context.Context, in *GetScoresRequest, opts ...grpc.CallOption) (*GetScoresResponse, error) {
	out := new(GetScoresResponse)
	err := c.cc.Invoke(ctx, LeaderboardsService_GetScores_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) SetScore(ctx context.Context, in *SetScoreRequest, opts ...grpc.CallOption) (*SetScoreResponse, error) {
	out := new(SetScoreResponse)
	err := c.cc.Invoke(ctx, LeaderboardsService_SetScore_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) IncrementScore(ctx context.Context, in *IncrementScoreRequest, opts ...grpc.CallOption) (*IncrementScoreResponse, error) {
	out := new(IncrementScoreResponse)
	err := c.cc.Invoke(ctx, LeaderboardsService_IncrementScore_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) BatchIncrementScore(ctx context.Context, in *BatchIncrementScoreRequest, opts ...grpc.CallOption) (*BatchIncrementScoreResponse, error) {
	out := new(BatchIncrementScoreResponse)
	err := c.cc.Invoke(ctx, LeaderboardsService_BatchIncrementScore_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) BatchSetScore(ctx context.Context, in *BatchSetScoreRequest, opts ...grpc.CallOption) (*BatchSetScoreResponse, error) {
	out := new(BatchSetScoreResponse)
	err := c.cc.Invoke(ctx, LeaderboardsService_BatchSetScore_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) BatchGetScores(ctx context.Context, in *BatchGetScoresRequest, opts ...grpc.CallOption) (*BatchGetScoresResponse, error) {
	out := new(BatchGetScoresResponse)
	err := c.cc.Invoke(ctx, LeaderboardsService_BatchGetScores_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) GetLeaderboards(ctx context.Context, in *GetLeaderboardsRequest, opts ...grpc.CallOption) (*GetLeaderboardsResponse, error) {
	out := new(GetLeaderboardsResponse)
	err := c.cc.Invoke(ctx, LeaderboardsService_GetLeaderboards_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) GetTieredLeaderboardDiagnostics(ctx context.Context, in *GetTieredLeaderboardDiagnosticsRequest, opts ...grpc.CallOption) (*TieredLeaderboardInfo, error) {
	out := new(TieredLeaderboardInfo)
	err := c.cc.Invoke(ctx, LeaderboardsService_GetTieredLeaderboardDiagnostics_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) GetUserData(ctx context.Context, in *GetUserDataRequest, opts ...grpc.CallOption) (*GetUserDataResponse, error) {
	out := new(GetUserDataResponse)
	err := c.cc.Invoke(ctx, LeaderboardsService_GetUserData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) DeleteUserData(ctx context.Context, in *DeleteUserDataRequest, opts ...grpc.CallOption) (*DeleteUserDataResponse, error) {
	out := new(DeleteUserDataResponse)
	err := c.cc.Invoke(ctx, LeaderboardsService_DeleteUserData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) CreateLeaderboard(ctx context.Context, in *CreateLeaderboardRequest, opts ...grpc.CallOption) (*CreateLeaderboardResponse, error) {
	out := new(CreateLeaderboardResponse)
	err := c.cc.Invoke(ctx, LeaderboardsService_CreateLeaderboard_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) UpdateLeaderboard(ctx context.Context, in *UpdateLeaderboardRequest, opts ...grpc.CallOption) (*UpdateLeaderboardResponse, error) {
	out := new(UpdateLeaderboardResponse)
	err := c.cc.Invoke(ctx, LeaderboardsService_UpdateLeaderboard_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) PatchLeaderboard(ctx context.Context, in *PatchLeaderboardRequest, opts ...grpc.CallOption) (*PatchLeaderboardResponse, error) {
	out := new(PatchLeaderboardResponse)
	err := c.cc.Invoke(ctx, LeaderboardsService_PatchLeaderboard_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) DeleteLeaderboard(ctx context.Context, in *DeleteLeaderboardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LeaderboardsService_DeleteLeaderboard_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) CleanupLeaderboard(ctx context.Context, in *CleanupLeaderboardRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LeaderboardsService_CleanupLeaderboard_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) ExportSettings(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SettingsImportExportData, error) {
	out := new(SettingsImportExportData)
	err := c.cc.Invoke(ctx, LeaderboardsService_ExportSettings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) ImportSettings(ctx context.Context, in *SettingsImportExportData, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LeaderboardsService_ImportSettings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leaderboardsServiceClient) ValidateImportSettings(ctx context.Context, in *SettingsImportExportData, opts ...grpc.CallOption) (*SettingsImportExportData, error) {
	out := new(SettingsImportExportData)
	err := c.cc.Invoke(ctx, LeaderboardsService_ValidateImportSettings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeaderboardsServiceServer is the server API for LeaderboardsService service.
// All implementations must embed UnimplementedLeaderboardsServiceServer
// for forward compatibility
type LeaderboardsServiceServer interface {
	GetScoresDeprecated(context.Context, *GetScoresRequest) (*GetScoresResponse, error)
	SetScoreDeprecated(context.Context, *SetScoreRequest) (*SetScoreResponse, error)
	IncrementScoreDeprecated(context.Context, *IncrementScoreRequest) (*IncrementScoreResponse, error)
	BatchIncrementScoreDeprecated(context.Context, *BatchIncrementScoreRequest) (*BatchIncrementScoreResponse, error)
	BatchSetScoreDeprecated(context.Context, *BatchSetScoreRequest) (*BatchSetScoreResponse, error)
	BatchGetScoresDeprecated(context.Context, *BatchGetScoresRequest) (*BatchGetScoresResponse, error)
	GetLeaderboardsDeprecated(context.Context, *GetLeaderboardsRequest) (*GetLeaderboardsResponse, error)
	CreateLeaderboardDeprecated(context.Context, *CreateLeaderboardRequest) (*CreateLeaderboardResponse, error)
	DeleteLeaderboardDeprecated(context.Context, *DeleteLeaderboardRequest) (*emptypb.Empty, error)
	// GetScores
	// GetScores
	//
	// GetScores gets the standings within a leaderboard
	GetScores(context.Context, *GetScoresRequest) (*GetScoresResponse, error)
	// SetScore
	//
	// SetScore updates the score on the leaderboard for the logged in user (if applicable)
	SetScore(context.Context, *SetScoreRequest) (*SetScoreResponse, error)
	// IncrementScore
	//
	// IncrementScore increments the score on the leaderboard for the logged in user
	IncrementScore(context.Context, *IncrementScoreRequest) (*IncrementScoreResponse, error)
	// BatchIncrementScore
	//
	// BatchIncrementScore increments the score on the leaderboard for the logged in user
	BatchIncrementScore(context.Context, *BatchIncrementScoreRequest) (*BatchIncrementScoreResponse, error)
	// BatchSetScore
	//
	// BatchSetScore updates the score on the leaderboard for the logged in user (if applicable)
	BatchSetScore(context.Context, *BatchSetScoreRequest) (*BatchSetScoreResponse, error)
	// BatchGetScore
	//
	// BatchGetScore gets the standings within a leaderboard
	BatchGetScores(context.Context, *BatchGetScoresRequest) (*BatchGetScoresResponse, error)
	// GetLeaderboards
	//
	// GetLeaderboards returns all the leaderboards within the cluster
	GetLeaderboards(context.Context, *GetLeaderboardsRequest) (*GetLeaderboardsResponse, error)
	GetTieredLeaderboardDiagnostics(context.Context, *GetTieredLeaderboardDiagnosticsRequest) (*TieredLeaderboardInfo, error)
	// GetUserData
	//
	// GetUserData returns all the leaderboards data for user within the cluster
	GetUserData(context.Context, *GetUserDataRequest) (*GetUserDataResponse, error)
	// DeleteUserData
	//
	// DeleteUserData deletes the leaderboard data for user
	DeleteUserData(context.Context, *DeleteUserDataRequest) (*DeleteUserDataResponse, error)
	// CreateLeaderboard
	//
	// CreateLeaderboard creates a new leaderboard with the given settings
	CreateLeaderboard(context.Context, *CreateLeaderboardRequest) (*CreateLeaderboardResponse, error)
	UpdateLeaderboard(context.Context, *UpdateLeaderboardRequest) (*UpdateLeaderboardResponse, error)
	PatchLeaderboard(context.Context, *PatchLeaderboardRequest) (*PatchLeaderboardResponse, error)
	DeleteLeaderboard(context.Context, *DeleteLeaderboardRequest) (*emptypb.Empty, error)
	CleanupLeaderboard(context.Context, *CleanupLeaderboardRequest) (*emptypb.Empty, error)
	ExportSettings(context.Context, *emptypb.Empty) (*SettingsImportExportData, error)
	ImportSettings(context.Context, *SettingsImportExportData) (*emptypb.Empty, error)
	ValidateImportSettings(context.Context, *SettingsImportExportData) (*SettingsImportExportData, error)
	mustEmbedUnimplementedLeaderboardsServiceServer()
}

// UnimplementedLeaderboardsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLeaderboardsServiceServer struct {
}

func (UnimplementedLeaderboardsServiceServer) GetScoresDeprecated(context.Context, *GetScoresRequest) (*GetScoresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScoresDeprecated not implemented")
}
func (UnimplementedLeaderboardsServiceServer) SetScoreDeprecated(context.Context, *SetScoreRequest) (*SetScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetScoreDeprecated not implemented")
}
func (UnimplementedLeaderboardsServiceServer) IncrementScoreDeprecated(context.Context, *IncrementScoreRequest) (*IncrementScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncrementScoreDeprecated not implemented")
}
func (UnimplementedLeaderboardsServiceServer) BatchIncrementScoreDeprecated(context.Context, *BatchIncrementScoreRequest) (*BatchIncrementScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchIncrementScoreDeprecated not implemented")
}
func (UnimplementedLeaderboardsServiceServer) BatchSetScoreDeprecated(context.Context, *BatchSetScoreRequest) (*BatchSetScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchSetScoreDeprecated not implemented")
}
func (UnimplementedLeaderboardsServiceServer) BatchGetScoresDeprecated(context.Context, *BatchGetScoresRequest) (*BatchGetScoresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetScoresDeprecated not implemented")
}
func (UnimplementedLeaderboardsServiceServer) GetLeaderboardsDeprecated(context.Context, *GetLeaderboardsRequest) (*GetLeaderboardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeaderboardsDeprecated not implemented")
}
func (UnimplementedLeaderboardsServiceServer) CreateLeaderboardDeprecated(context.Context, *CreateLeaderboardRequest) (*CreateLeaderboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLeaderboardDeprecated not implemented")
}
func (UnimplementedLeaderboardsServiceServer) DeleteLeaderboardDeprecated(context.Context, *DeleteLeaderboardRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLeaderboardDeprecated not implemented")
}
func (UnimplementedLeaderboardsServiceServer) GetScores(context.Context, *GetScoresRequest) (*GetScoresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetScores not implemented")
}
func (UnimplementedLeaderboardsServiceServer) SetScore(context.Context, *SetScoreRequest) (*SetScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetScore not implemented")
}
func (UnimplementedLeaderboardsServiceServer) IncrementScore(context.Context, *IncrementScoreRequest) (*IncrementScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncrementScore not implemented")
}
func (UnimplementedLeaderboardsServiceServer) BatchIncrementScore(context.Context, *BatchIncrementScoreRequest) (*BatchIncrementScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchIncrementScore not implemented")
}
func (UnimplementedLeaderboardsServiceServer) BatchSetScore(context.Context, *BatchSetScoreRequest) (*BatchSetScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchSetScore not implemented")
}
func (UnimplementedLeaderboardsServiceServer) BatchGetScores(context.Context, *BatchGetScoresRequest) (*BatchGetScoresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetScores not implemented")
}
func (UnimplementedLeaderboardsServiceServer) GetLeaderboards(context.Context, *GetLeaderboardsRequest) (*GetLeaderboardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLeaderboards not implemented")
}
func (UnimplementedLeaderboardsServiceServer) GetTieredLeaderboardDiagnostics(context.Context, *GetTieredLeaderboardDiagnosticsRequest) (*TieredLeaderboardInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTieredLeaderboardDiagnostics not implemented")
}
func (UnimplementedLeaderboardsServiceServer) GetUserData(context.Context, *GetUserDataRequest) (*GetUserDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserData not implemented")
}
func (UnimplementedLeaderboardsServiceServer) DeleteUserData(context.Context, *DeleteUserDataRequest) (*DeleteUserDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserData not implemented")
}
func (UnimplementedLeaderboardsServiceServer) CreateLeaderboard(context.Context, *CreateLeaderboardRequest) (*CreateLeaderboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLeaderboard not implemented")
}
func (UnimplementedLeaderboardsServiceServer) UpdateLeaderboard(context.Context, *UpdateLeaderboardRequest) (*UpdateLeaderboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLeaderboard not implemented")
}
func (UnimplementedLeaderboardsServiceServer) PatchLeaderboard(context.Context, *PatchLeaderboardRequest) (*PatchLeaderboardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatchLeaderboard not implemented")
}
func (UnimplementedLeaderboardsServiceServer) DeleteLeaderboard(context.Context, *DeleteLeaderboardRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLeaderboard not implemented")
}
func (UnimplementedLeaderboardsServiceServer) CleanupLeaderboard(context.Context, *CleanupLeaderboardRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CleanupLeaderboard not implemented")
}
func (UnimplementedLeaderboardsServiceServer) ExportSettings(context.Context, *emptypb.Empty) (*SettingsImportExportData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportSettings not implemented")
}
func (UnimplementedLeaderboardsServiceServer) ImportSettings(context.Context, *SettingsImportExportData) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportSettings not implemented")
}
func (UnimplementedLeaderboardsServiceServer) ValidateImportSettings(context.Context, *SettingsImportExportData) (*SettingsImportExportData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateImportSettings not implemented")
}
func (UnimplementedLeaderboardsServiceServer) mustEmbedUnimplementedLeaderboardsServiceServer() {}

// UnsafeLeaderboardsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LeaderboardsServiceServer will
// result in compilation errors.
type UnsafeLeaderboardsServiceServer interface {
	mustEmbedUnimplementedLeaderboardsServiceServer()
}

func RegisterLeaderboardsServiceServer(s grpc.ServiceRegistrar, srv LeaderboardsServiceServer) {
	s.RegisterService(&LeaderboardsService_ServiceDesc, srv)
}

func _LeaderboardsService_GetScoresDeprecated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).GetScoresDeprecated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_GetScoresDeprecated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).GetScoresDeprecated(ctx, req.(*GetScoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_SetScoreDeprecated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).SetScoreDeprecated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_SetScoreDeprecated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).SetScoreDeprecated(ctx, req.(*SetScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_IncrementScoreDeprecated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrementScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).IncrementScoreDeprecated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_IncrementScoreDeprecated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).IncrementScoreDeprecated(ctx, req.(*IncrementScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_BatchIncrementScoreDeprecated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchIncrementScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).BatchIncrementScoreDeprecated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_BatchIncrementScoreDeprecated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).BatchIncrementScoreDeprecated(ctx, req.(*BatchIncrementScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_BatchSetScoreDeprecated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchSetScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).BatchSetScoreDeprecated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_BatchSetScoreDeprecated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).BatchSetScoreDeprecated(ctx, req.(*BatchSetScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_BatchGetScoresDeprecated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetScoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).BatchGetScoresDeprecated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_BatchGetScoresDeprecated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).BatchGetScoresDeprecated(ctx, req.(*BatchGetScoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_GetLeaderboardsDeprecated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaderboardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).GetLeaderboardsDeprecated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_GetLeaderboardsDeprecated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).GetLeaderboardsDeprecated(ctx, req.(*GetLeaderboardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_CreateLeaderboardDeprecated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).CreateLeaderboardDeprecated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_CreateLeaderboardDeprecated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).CreateLeaderboardDeprecated(ctx, req.(*CreateLeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_DeleteLeaderboardDeprecated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).DeleteLeaderboardDeprecated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_DeleteLeaderboardDeprecated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).DeleteLeaderboardDeprecated(ctx, req.(*DeleteLeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_GetScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).GetScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_GetScores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).GetScores(ctx, req.(*GetScoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_SetScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).SetScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_SetScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).SetScore(ctx, req.(*SetScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_IncrementScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrementScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).IncrementScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_IncrementScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).IncrementScore(ctx, req.(*IncrementScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_BatchIncrementScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchIncrementScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).BatchIncrementScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_BatchIncrementScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).BatchIncrementScore(ctx, req.(*BatchIncrementScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_BatchSetScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchSetScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).BatchSetScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_BatchSetScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).BatchSetScore(ctx, req.(*BatchSetScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_BatchGetScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetScoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).BatchGetScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_BatchGetScores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).BatchGetScores(ctx, req.(*BatchGetScoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_GetLeaderboards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLeaderboardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).GetLeaderboards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_GetLeaderboards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).GetLeaderboards(ctx, req.(*GetLeaderboardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_GetTieredLeaderboardDiagnostics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTieredLeaderboardDiagnosticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).GetTieredLeaderboardDiagnostics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_GetTieredLeaderboardDiagnostics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).GetTieredLeaderboardDiagnostics(ctx, req.(*GetTieredLeaderboardDiagnosticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_GetUserData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).GetUserData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_GetUserData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).GetUserData(ctx, req.(*GetUserDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_DeleteUserData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).DeleteUserData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_DeleteUserData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).DeleteUserData(ctx, req.(*DeleteUserDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_CreateLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).CreateLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_CreateLeaderboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).CreateLeaderboard(ctx, req.(*CreateLeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_UpdateLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).UpdateLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_UpdateLeaderboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).UpdateLeaderboard(ctx, req.(*UpdateLeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_PatchLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchLeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).PatchLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_PatchLeaderboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).PatchLeaderboard(ctx, req.(*PatchLeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_DeleteLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).DeleteLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_DeleteLeaderboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).DeleteLeaderboard(ctx, req.(*DeleteLeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_CleanupLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanupLeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).CleanupLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_CleanupLeaderboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).CleanupLeaderboard(ctx, req.(*CleanupLeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_ExportSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).ExportSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_ExportSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).ExportSettings(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_ImportSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsImportExportData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).ImportSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_ImportSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).ImportSettings(ctx, req.(*SettingsImportExportData))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeaderboardsService_ValidateImportSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsImportExportData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeaderboardsServiceServer).ValidateImportSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LeaderboardsService_ValidateImportSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeaderboardsServiceServer).ValidateImportSettings(ctx, req.(*SettingsImportExportData))
	}
	return interceptor(ctx, in, info, handler)
}

// LeaderboardsService_ServiceDesc is the grpc.ServiceDesc for LeaderboardsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LeaderboardsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "leaderboards.LeaderboardsService",
	HandlerType: (*LeaderboardsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetScoresDeprecated",
			Handler:    _LeaderboardsService_GetScoresDeprecated_Handler,
		},
		{
			MethodName: "SetScoreDeprecated",
			Handler:    _LeaderboardsService_SetScoreDeprecated_Handler,
		},
		{
			MethodName: "IncrementScoreDeprecated",
			Handler:    _LeaderboardsService_IncrementScoreDeprecated_Handler,
		},
		{
			MethodName: "BatchIncrementScoreDeprecated",
			Handler:    _LeaderboardsService_BatchIncrementScoreDeprecated_Handler,
		},
		{
			MethodName: "BatchSetScoreDeprecated",
			Handler:    _LeaderboardsService_BatchSetScoreDeprecated_Handler,
		},
		{
			MethodName: "BatchGetScoresDeprecated",
			Handler:    _LeaderboardsService_BatchGetScoresDeprecated_Handler,
		},
		{
			MethodName: "GetLeaderboardsDeprecated",
			Handler:    _LeaderboardsService_GetLeaderboardsDeprecated_Handler,
		},
		{
			MethodName: "CreateLeaderboardDeprecated",
			Handler:    _LeaderboardsService_CreateLeaderboardDeprecated_Handler,
		},
		{
			MethodName: "DeleteLeaderboardDeprecated",
			Handler:    _LeaderboardsService_DeleteLeaderboardDeprecated_Handler,
		},
		{
			MethodName: "GetScores",
			Handler:    _LeaderboardsService_GetScores_Handler,
		},
		{
			MethodName: "SetScore",
			Handler:    _LeaderboardsService_SetScore_Handler,
		},
		{
			MethodName: "IncrementScore",
			Handler:    _LeaderboardsService_IncrementScore_Handler,
		},
		{
			MethodName: "BatchIncrementScore",
			Handler:    _LeaderboardsService_BatchIncrementScore_Handler,
		},
		{
			MethodName: "BatchSetScore",
			Handler:    _LeaderboardsService_BatchSetScore_Handler,
		},
		{
			MethodName: "BatchGetScores",
			Handler:    _LeaderboardsService_BatchGetScores_Handler,
		},
		{
			MethodName: "GetLeaderboards",
			Handler:    _LeaderboardsService_GetLeaderboards_Handler,
		},
		{
			MethodName: "GetTieredLeaderboardDiagnostics",
			Handler:    _LeaderboardsService_GetTieredLeaderboardDiagnostics_Handler,
		},
		{
			MethodName: "GetUserData",
			Handler:    _LeaderboardsService_GetUserData_Handler,
		},
		{
			MethodName: "DeleteUserData",
			Handler:    _LeaderboardsService_DeleteUserData_Handler,
		},
		{
			MethodName: "CreateLeaderboard",
			Handler:    _LeaderboardsService_CreateLeaderboard_Handler,
		},
		{
			MethodName: "UpdateLeaderboard",
			Handler:    _LeaderboardsService_UpdateLeaderboard_Handler,
		},
		{
			MethodName: "PatchLeaderboard",
			Handler:    _LeaderboardsService_PatchLeaderboard_Handler,
		},
		{
			MethodName: "DeleteLeaderboard",
			Handler:    _LeaderboardsService_DeleteLeaderboard_Handler,
		},
		{
			MethodName: "CleanupLeaderboard",
			Handler:    _LeaderboardsService_CleanupLeaderboard_Handler,
		},
		{
			MethodName: "ExportSettings",
			Handler:    _LeaderboardsService_ExportSettings_Handler,
		},
		{
			MethodName: "ImportSettings",
			Handler:    _LeaderboardsService_ImportSettings_Handler,
		},
		{
			MethodName: "ValidateImportSettings",
			Handler:    _LeaderboardsService_ValidateImportSettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "leaderboards_services.proto",
}
