class_name MbHermesClient
extends Node

## Validator client over the Snapser Hermes WebSocket envelope. One codepath
## for both targets — only the URL differs:
##   local dev:  ws://localhost:5555/hermes/ws?token=<player_id>
##               (the validator's Hermes-emulation endpoint; the token is the
##               self-stamped player id, no gateway)
##   deployed:   wss://gateway.snapser.com/<snapend>/v1/hermes/ws?token=<session>
##               (the real Hermes; the token is the Snapser session token, so
##               this also works from web exports where WS headers are blocked)
##
## Wire format: binary protobuf frames — hermes.ClientMessage out,
## hermes.ServerMessage in (bindings generated by godobuf from
## validator/protos/; see game/net/proto/README.md). RPC payloads are the
## moveborne.validator.v1 messages; requests are correlated by `mid`.
##
## Do NOT send Message_Ping: the live Hermes endpoint drops the connection on
## client pings (observed 2026-06-11). WS protocol keepalive suffices.

const HermesPb := preload("res://net/proto/hermes_envelope_pb.gd")
const ValidatorPb := preload("res://net/proto/validator_pb.gd")

# Hermes resolves the package segment to a snap id, so deployed routing needs
# the BYOSnap-id-shaped name (live-verified); the validator registers it as an
# alias of the canonical moveborne.validator.v1.ValidatorService, and the local
# emulation endpoint accepts both.
const SERVICE := "/byosnap-validator.ValidatorService"

## ServerMessage oneof case tags (field numbers in hermes_envelope.proto).
const CASE_PONG := 10
const CASE_ERROR := 11
const CASE_API_RESPONSE := 50

signal ready_received(current_state: Dictionary)
signal action_validated(index: int, matched: bool, corrected_state)   # matched=true => keep optimistic; else corrected_state is the authoritative state
signal match_completed(response: Dictionary)   # CompleteMatch: {match_id, rewards, balances, granted}
signal validator_error(message: String)
signal connected()

var _ws := WebSocketPeer.new()
var _polling := false
var _opened := false
var _ready_ok := false
var _match_id := ""
var _player_id := ""
var _mode := "story"
var _starting_state: Dictionary = {}
var _mid := 0
var _pending: Dictionary = {}   # mid -> {kind: String, index: int}


## Connect to a Hermes(-compatible) WSS endpoint and register the match: on the
## socket opening, InitMatch is sent; its response fires connected() +
## ready_received(state). `ws_url` must already carry the ?token= query param.
func init_and_connect(ws_url: String, match_id: String, starting_state: Dictionary, player_id: String, mode: String = "story") -> void:
	_match_id = match_id
	_player_id = player_id
	_mode = mode
	_starting_state = starting_state
	_opened = false
	_ready_ok = false
	_pending.clear()
	var err := _ws.connect_to_url(ws_url)
	if err != OK:
		validator_error.emit("WS connect failed: %d" % err)
		return
	_polling = true
	set_process(true)


func _process(_delta: float) -> void:
	if not _polling:
		return
	_ws.poll()
	match _ws.get_ready_state():
		WebSocketPeer.STATE_OPEN:
			if not _opened:
				_opened = true
				_send_init()
			while _ws.get_available_packet_count() > 0:
				var pkt := _ws.get_packet()
				if not _ws.was_string_packet():
					_handle_frame(pkt)
		WebSocketPeer.STATE_CLOSED:
			_polling = false
			set_process(false)
			validator_error.emit("WS closed: %d %s" % [_ws.get_close_code(), _ws.get_close_reason()])


## Validate one optimistic action; fires action_validated(index, matched, state).
func validate_action(index: int, action: Dictionary, state_hash: String) -> void:
	var req := ValidatorPb.ValidateActionRequest.new()
	req.set_match_id(_match_id)
	req.set_index(index)
	req.set_action_json(JSON.stringify(action))
	req.set_state_hash(state_hash)
	_call(SERVICE + "/ValidateAction", req.to_bytes(), {"kind": "action", "index": index})


## Settle the match (idempotent server-side): the validator computes currency
## rewards from ITS validated state and awards them s2s. On the response fires
## match_completed({match_id, rewards, balances, granted}). Safe to call only
## once ready; returns false otherwise so callers can skip waiting.
func complete_match() -> bool:
	if not _ready_ok:
		return false
	var req := ValidatorPb.CompleteMatchRequest.new()
	req.set_match_id(_match_id)
	_call(SERVICE + "/CompleteMatch", req.to_bytes(), {"kind": "complete"})
	return true


func _send_init() -> void:
	var req := ValidatorPb.InitMatchRequest.new()
	req.set_match_id(_match_id)
	req.set_starting_state_json(JSON.stringify(_starting_state))
	req.set_player_id(_player_id)
	req.set_mode(_mode)
	_call(SERVICE + "/InitMatch", req.to_bytes(), {"kind": "init"})


func _call(method: String, payload: PackedByteArray, pending: Dictionary) -> void:
	var mid := "mb-%d" % _mid
	_mid += 1
	_pending[mid] = pending
	var cm := HermesPb.ClientMessage.new()
	cm.set_mid(mid)
	cm.set_message_type(HermesPb.MessageType.SNAP_API_PROXY)
	cm.set_timestamp(int(Time.get_unix_time_from_system()))
	var req := cm.new_snap_api_request()
	req.set_api_method(method)
	req.set_payload(payload)
	_ws.send(cm.to_bytes())


func _handle_frame(bytes: PackedByteArray) -> void:
	var sm := HermesPb.ServerMessage.new()
	if sm.from_bytes(bytes) != HermesPb.PB_ERR.NO_ERRORS:
		validator_error.emit("bad ServerMessage frame")
		return
	match sm.get_msg_case():
		CASE_API_RESPONSE:
			_handle_api_response(sm)
		CASE_ERROR:
			# Hermes-level routing error (e.g. "invalid service"); drop the
			# pending request — it will never be answered.
			_pending.erase(sm.get_mid())
			var e := sm.get_error()
			validator_error.emit("hermes error %d: %s" % [e.get_code(), e.get_error_message()])
		CASE_PONG:
			pass
		_:
			pass  # snap events / notifications — not used by the validator


func _handle_api_response(sm) -> void:
	var mid: String = sm.get_mid()
	if not _pending.has(mid):
		return
	var pending: Dictionary = _pending[mid]
	_pending.erase(mid)
	var resp = sm.get_api_response()
	if resp.get_is_error():
		var detail := "api error"
		if resp.has_error():
			var e = resp.get_error()
			detail = "%s (code %d)" % [e.get_error_message(), e.get_code()]
		validator_error.emit("%s: %s" % [str(pending.get("kind", "?")), detail])
		return
	var payload: PackedByteArray = resp.get_payload()
	match str(pending.get("kind", "")):
		"init":
			var init := ValidatorPb.InitMatchResponse.new()
			if init.from_bytes(payload) != ValidatorPb.PB_ERR.NO_ERRORS:
				validator_error.emit("bad InitMatchResponse")
				return
			_ready_ok = true
			connected.emit()
			var state = JSON.parse_string(init.get_current_state_json())
			ready_received.emit(state if state is Dictionary else {})
		"action":
			var val := ValidatorPb.ValidateActionResponse.new()
			if val.from_bytes(payload) != ValidatorPb.PB_ERR.NO_ERRORS:
				validator_error.emit("bad ValidateActionResponse")
				return
			var index: int = int(pending.get("index", val.get_index()))
			if val.get_matched():
				action_validated.emit(index, true, null)
			else:
				var corrected = JSON.parse_string(val.get_state_json())
				action_validated.emit(index, false, corrected)
		"complete":
			var done := ValidatorPb.CompleteMatchResponse.new()
			if done.from_bytes(payload) != ValidatorPb.PB_ERR.NO_ERRORS:
				validator_error.emit("bad CompleteMatchResponse")
				return
			match_completed.emit({
				"match_id": done.get_match_id(),
				"rewards": done.get_rewards(),
				"balances": done.get_balances(),
				"granted": done.get_granted(),
			})
