// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: hermes_services.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	HermesService_FinderForwardMessage_FullMethodName = "/hermes.HermesService/FinderForwardMessage"
	HermesService_NotifyUser_FullMethodName           = "/hermes.HermesService/NotifyUser"
	HermesService_Notify_FullMethodName               = "/hermes.HermesService/Notify"
	HermesService_ServerBroadcastMsg_FullMethodName   = "/hermes.HermesService/ServerBroadcastMsg"
	HermesService_GetUserPresences_FullMethodName     = "/hermes.HermesService/GetUserPresences"
	HermesService_GetNodePresences_FullMethodName     = "/hermes.HermesService/GetNodePresences"
)

// HermesServiceClient is the client API for HermesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HermesServiceClient interface {
	FinderForwardMessage(ctx context.Context, in *FinderForwardMessageRequest, opts ...grpc.CallOption) (*FinderForwardMessageResponse, error)
	NotifyUser(ctx context.Context, in *NotifyUserRequest, opts ...grpc.CallOption) (*NotifyUserResponse, error)
	Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error)
	ServerBroadcastMsg(ctx context.Context, in *ServerBroadcastMsgRequest, opts ...grpc.CallOption) (*ServerBroadcastMsgResponse, error)
	GetUserPresences(ctx context.Context, in *GetUserPresencesRequest, opts ...grpc.CallOption) (*GetUserPresencesResponse, error)
	GetNodePresences(ctx context.Context, in *GetNodePresencesRequest, opts ...grpc.CallOption) (*GetNodePresencesResponse, error)
}

type hermesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHermesServiceClient(cc grpc.ClientConnInterface) HermesServiceClient {
	return &hermesServiceClient{cc}
}

func (c *hermesServiceClient) FinderForwardMessage(ctx context.Context, in *FinderForwardMessageRequest, opts ...grpc.CallOption) (*FinderForwardMessageResponse, error) {
	out := new(FinderForwardMessageResponse)
	err := c.cc.Invoke(ctx, HermesService_FinderForwardMessage_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hermesServiceClient) NotifyUser(ctx context.Context, in *NotifyUserRequest, opts ...grpc.CallOption) (*NotifyUserResponse, error) {
	out := new(NotifyUserResponse)
	err := c.cc.Invoke(ctx, HermesService_NotifyUser_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hermesServiceClient) Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error) {
	out := new(NotifyResponse)
	err := c.cc.Invoke(ctx, HermesService_Notify_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hermesServiceClient) ServerBroadcastMsg(ctx context.Context, in *ServerBroadcastMsgRequest, opts ...grpc.CallOption) (*ServerBroadcastMsgResponse, error) {
	out := new(ServerBroadcastMsgResponse)
	err := c.cc.Invoke(ctx, HermesService_ServerBroadcastMsg_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hermesServiceClient) GetUserPresences(ctx context.Context, in *GetUserPresencesRequest, opts ...grpc.CallOption) (*GetUserPresencesResponse, error) {
	out := new(GetUserPresencesResponse)
	err := c.cc.Invoke(ctx, HermesService_GetUserPresences_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hermesServiceClient) GetNodePresences(ctx context.Context, in *GetNodePresencesRequest, opts ...grpc.CallOption) (*GetNodePresencesResponse, error) {
	out := new(GetNodePresencesResponse)
	err := c.cc.Invoke(ctx, HermesService_GetNodePresences_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HermesServiceServer is the server API for HermesService service.
// All implementations must embed UnimplementedHermesServiceServer
// for forward compatibility
type HermesServiceServer interface {
	FinderForwardMessage(context.Context, *FinderForwardMessageRequest) (*FinderForwardMessageResponse, error)
	NotifyUser(context.Context, *NotifyUserRequest) (*NotifyUserResponse, error)
	Notify(context.Context, *NotifyRequest) (*NotifyResponse, error)
	ServerBroadcastMsg(context.Context, *ServerBroadcastMsgRequest) (*ServerBroadcastMsgResponse, error)
	GetUserPresences(context.Context, *GetUserPresencesRequest) (*GetUserPresencesResponse, error)
	GetNodePresences(context.Context, *GetNodePresencesRequest) (*GetNodePresencesResponse, error)
	mustEmbedUnimplementedHermesServiceServer()
}

// UnimplementedHermesServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHermesServiceServer struct {
}

func (UnimplementedHermesServiceServer) FinderForwardMessage(context.Context, *FinderForwardMessageRequest) (*FinderForwardMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinderForwardMessage not implemented")
}
func (UnimplementedHermesServiceServer) NotifyUser(context.Context, *NotifyUserRequest) (*NotifyUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyUser not implemented")
}
func (UnimplementedHermesServiceServer) Notify(context.Context, *NotifyRequest) (*NotifyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Notify not implemented")
}
func (UnimplementedHermesServiceServer) ServerBroadcastMsg(context.Context, *ServerBroadcastMsgRequest) (*ServerBroadcastMsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ServerBroadcastMsg not implemented")
}
func (UnimplementedHermesServiceServer) GetUserPresences(context.Context, *GetUserPresencesRequest) (*GetUserPresencesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserPresences not implemented")
}
func (UnimplementedHermesServiceServer) GetNodePresences(context.Context, *GetNodePresencesRequest) (*GetNodePresencesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodePresences not implemented")
}
func (UnimplementedHermesServiceServer) mustEmbedUnimplementedHermesServiceServer() {}

// UnsafeHermesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HermesServiceServer will
// result in compilation errors.
type UnsafeHermesServiceServer interface {
	mustEmbedUnimplementedHermesServiceServer()
}

func RegisterHermesServiceServer(s grpc.ServiceRegistrar, srv HermesServiceServer) {
	s.RegisterService(&HermesService_ServiceDesc, srv)
}

func _HermesService_FinderForwardMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinderForwardMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HermesServiceServer).FinderForwardMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HermesService_FinderForwardMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HermesServiceServer).FinderForwardMessage(ctx, req.(*FinderForwardMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HermesService_NotifyUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HermesServiceServer).NotifyUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HermesService_NotifyUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HermesServiceServer).NotifyUser(ctx, req.(*NotifyUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HermesService_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HermesServiceServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HermesService_Notify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HermesServiceServer).Notify(ctx, req.(*NotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HermesService_ServerBroadcastMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerBroadcastMsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HermesServiceServer).ServerBroadcastMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HermesService_ServerBroadcastMsg_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HermesServiceServer).ServerBroadcastMsg(ctx, req.(*ServerBroadcastMsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HermesService_GetUserPresences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserPresencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HermesServiceServer).GetUserPresences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HermesService_GetUserPresences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HermesServiceServer).GetUserPresences(ctx, req.(*GetUserPresencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HermesService_GetNodePresences_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodePresencesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HermesServiceServer).GetNodePresences(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HermesService_GetNodePresences_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HermesServiceServer).GetNodePresences(ctx, req.(*GetNodePresencesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HermesService_ServiceDesc is the grpc.ServiceDesc for HermesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HermesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hermes.HermesService",
	HandlerType: (*HermesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FinderForwardMessage",
			Handler:    _HermesService_FinderForwardMessage_Handler,
		},
		{
			MethodName: "NotifyUser",
			Handler:    _HermesService_NotifyUser_Handler,
		},
		{
			MethodName: "Notify",
			Handler:    _HermesService_Notify_Handler,
		},
		{
			MethodName: "ServerBroadcastMsg",
			Handler:    _HermesService_ServerBroadcastMsg_Handler,
		},
		{
			MethodName: "GetUserPresences",
			Handler:    _HermesService_GetUserPresences_Handler,
		},
		{
			MethodName: "GetNodePresences",
			Handler:    _HermesService_GetNodePresences_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hermes_services.proto",
}
