// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: quests_services.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	QuestsService_CreateQuest_FullMethodName                = "/quests.QuestsService/CreateQuest"
	QuestsService_GetQuests_FullMethodName                  = "/quests.QuestsService/GetQuests"
	QuestsService_GetQuest_FullMethodName                   = "/quests.QuestsService/GetQuest"
	QuestsService_DeleteQuest_FullMethodName                = "/quests.QuestsService/DeleteQuest"
	QuestsService_UpdateQuest_FullMethodName                = "/quests.QuestsService/UpdateQuest"
	QuestsService_AddTaskToQuest_FullMethodName             = "/quests.QuestsService/AddTaskToQuest"
	QuestsService_RemoveTaskFromQuest_FullMethodName        = "/quests.QuestsService/RemoveTaskFromQuest"
	QuestsService_GetAvailableQuests_FullMethodName         = "/quests.QuestsService/GetAvailableQuests"
	QuestsService_GetActiveQuests_FullMethodName            = "/quests.QuestsService/GetActiveQuests"
	QuestsService_BatchGetActiveQuests_FullMethodName       = "/quests.QuestsService/BatchGetActiveQuests"
	QuestsService_AssignQuest_FullMethodName                = "/quests.QuestsService/AssignQuest"
	QuestsService_DeleteUserQuest_FullMethodName            = "/quests.QuestsService/DeleteUserQuest"
	QuestsService_IncrementTaskProgress_FullMethodName      = "/quests.QuestsService/IncrementTaskProgress"
	QuestsService_UpdateTaskMetadata_FullMethodName         = "/quests.QuestsService/UpdateTaskMetadata"
	QuestsService_BatchIncrementTaskProgress_FullMethodName = "/quests.QuestsService/BatchIncrementTaskProgress"
	QuestsService_EnableQuest_FullMethodName                = "/quests.QuestsService/EnableQuest"
	QuestsService_DisableQuest_FullMethodName               = "/quests.QuestsService/DisableQuest"
	QuestsService_UpdateProgressCallback_FullMethodName     = "/quests.QuestsService/UpdateProgressCallback"
	QuestsService_ClaimQuestRewards_FullMethodName          = "/quests.QuestsService/ClaimQuestRewards"
	QuestsService_ClaimTaskRewards_FullMethodName           = "/quests.QuestsService/ClaimTaskRewards"
	QuestsService_BatchClaimQuestRewards_FullMethodName     = "/quests.QuestsService/BatchClaimQuestRewards"
	QuestsService_BatchClaimTaskRewards_FullMethodName      = "/quests.QuestsService/BatchClaimTaskRewards"
	QuestsService_GetUserData_FullMethodName                = "/quests.QuestsService/GetUserData"
	QuestsService_DeleteUserData_FullMethodName             = "/quests.QuestsService/DeleteUserData"
	QuestsService_ExportSettings_FullMethodName             = "/quests.QuestsService/ExportSettings"
	QuestsService_ImportSettings_FullMethodName             = "/quests.QuestsService/ImportSettings"
	QuestsService_ValidateImportSettings_FullMethodName     = "/quests.QuestsService/ValidateImportSettings"
)

// QuestsServiceClient is the client API for QuestsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuestsServiceClient interface {
	// create a quest
	CreateQuest(ctx context.Context, in *CreateQuestRequest, opts ...grpc.CallOption) (*Quest, error)
	// get all quests
	GetQuests(ctx context.Context, in *GetQuestsRequest, opts ...grpc.CallOption) (*GetQuestsResponse, error)
	// get a quest by name
	GetQuest(ctx context.Context, in *GetQuestRequest, opts ...grpc.CallOption) (*Quest, error)
	// delete a quest
	DeleteQuest(ctx context.Context, in *DeleteQuestRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateQuest(ctx context.Context, in *UpdateQuestRequest, opts ...grpc.CallOption) (*Quest, error)
	// add task to a quest
	AddTaskToQuest(ctx context.Context, in *AddTaskToQuestRequest, opts ...grpc.CallOption) (*Task, error)
	// delete a task from a quest
	RemoveTaskFromQuest(ctx context.Context, in *RemoveTaskRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// get available quests for user
	GetAvailableQuests(ctx context.Context, in *GetAvailableQuestsRequest, opts ...grpc.CallOption) (*GetAvailableQuestsResponse, error)
	// get active quests for user
	GetActiveQuests(ctx context.Context, in *GetActiveQuestsRequest, opts ...grpc.CallOption) (*UserQuests, error)
	// BatchGetActiveQuests
	BatchGetActiveQuests(ctx context.Context, in *BatchGetActiveQuestsRequest, opts ...grpc.CallOption) (*BatchGetActiveQuestsResponse, error)
	// assign a quest to a user
	AssignQuest(ctx context.Context, in *AssignQuestRequest, opts ...grpc.CallOption) (*UserQuest, error)
	// delete user quest
	DeleteUserQuest(ctx context.Context, in *DeleteUserQuestRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// update progress of a task in a quest for a user
	IncrementTaskProgress(ctx context.Context, in *IncrementTaskProgressRequest, opts ...grpc.CallOption) (*UserQuest, error)
	// Update user metadata to a task in a quest assigned to a user
	UpdateTaskMetadata(ctx context.Context, in *UpdateTaskMetadataRequest, opts ...grpc.CallOption) (*UserQuest, error)
	// BatchIncrementTaskProgress
	BatchIncrementTaskProgress(ctx context.Context, in *BatchIncrementTaskProgressRequest, opts ...grpc.CallOption) (*BatchIncrementTaskProgressResponse, error)
	// enable quest
	EnableQuest(ctx context.Context, in *EnableQuestRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// disable quest
	DisableQuest(ctx context.Context, in *DisableQuestRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateProgressCallback(ctx context.Context, in *CallbackRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ClaimQuestRewards(ctx context.Context, in *ClaimQuestRewardsRequest, opts ...grpc.CallOption) (*ClaimQuestRewardsResponse, error)
	ClaimTaskRewards(ctx context.Context, in *ClaimTaskRewardsRequest, opts ...grpc.CallOption) (*ClaimTaskRewardsResponse, error)
	BatchClaimQuestRewards(ctx context.Context, in *BatchClaimQuestRewardsRequest, opts ...grpc.CallOption) (*BatchClaimQuestRewardsResponse, error)
	BatchClaimTaskRewards(ctx context.Context, in *BatchClaimTaskRewardsRequest, opts ...grpc.CallOption) (*BatchClaimTaskRewardsResponse, error)
	GetUserData(ctx context.Context, in *UserDataRequest, opts ...grpc.CallOption) (*UserQuests, error)
	DeleteUserData(ctx context.Context, in *UserDataRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ExportSettings(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SettingsImportExportData, error)
	ImportSettings(ctx context.Context, in *SettingsImportExportData, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ValidateImportSettings(ctx context.Context, in *SettingsImportExportData, opts ...grpc.CallOption) (*SettingsImportExportData, error)
}

type questsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuestsServiceClient(cc grpc.ClientConnInterface) QuestsServiceClient {
	return &questsServiceClient{cc}
}

func (c *questsServiceClient) CreateQuest(ctx context.Context, in *CreateQuestRequest, opts ...grpc.CallOption) (*Quest, error) {
	out := new(Quest)
	err := c.cc.Invoke(ctx, QuestsService_CreateQuest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questsServiceClient) GetQuests(ctx context.Context, in *GetQuestsRequest, opts ...grpc.CallOption) (*GetQuestsResponse, error) {
	out := new(GetQuestsResponse)
	err := c.cc.Invoke(ctx, QuestsService_GetQuests_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questsServiceClient) GetQuest(ctx context.Context, in *GetQuestRequest, opts ...grpc.CallOption) (*Quest, error) {
	out := new(Quest)
	err := c.cc.Invoke(ctx, QuestsService_GetQuest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questsServiceClient) DeleteQuest(ctx context.Context, in *DeleteQuestRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, QuestsService_DeleteQuest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questsServiceClient) UpdateQuest(ctx context.Context, in *UpdateQuestRequest, opts ...grpc.CallOption) (*Quest, error) {
	out := new(Quest)
	err := c.cc.Invoke(ctx, QuestsService_UpdateQuest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questsServiceClient) AddTaskToQuest(ctx context.Context, in *AddTaskToQuestRequest, opts ...grpc.CallOption) (*Task, error) {
	out := new(Task)
	err := c.cc.Invoke(ctx, QuestsService_AddTaskToQuest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questsServiceClient) RemoveTaskFromQuest(ctx context.Context, in *RemoveTaskRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, QuestsService_RemoveTaskFromQuest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questsServiceClient) GetAvailableQuests(ctx context.Context, in *GetAvailableQuestsRequest, opts ...grpc.CallOption) (*GetAvailableQuestsResponse, error) {
	out := new(GetAvailableQuestsResponse)
	err := c.cc.Invoke(ctx, QuestsService_GetAvailableQuests_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questsServiceClient) GetActiveQuests(ctx context.Context, in *GetActiveQuestsRequest, opts ...grpc.CallOption) (*UserQuests, error) {
	out := new(UserQuests)
	err := c.cc.Invoke(ctx, QuestsService_GetActiveQuests_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questsServiceClient) BatchGetActiveQuests(ctx context.Context, in *BatchGetActiveQuestsRequest, opts ...grpc.CallOption) (*BatchGetActiveQuestsResponse, error) {
	out := new(BatchGetActiveQuestsResponse)
	err := c.cc.Invoke(ctx, QuestsService_BatchGetActiveQuests_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questsServiceClient) AssignQuest(ctx context.Context, in *AssignQuestRequest, opts ...grpc.CallOption) (*UserQuest, error) {
	out := new(UserQuest)
	err := c.cc.Invoke(ctx, QuestsService_AssignQuest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questsServiceClient) DeleteUserQuest(ctx context.Context, in *DeleteUserQuestRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, QuestsService_DeleteUserQuest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questsServiceClient) IncrementTaskProgress(ctx context.Context, in *IncrementTaskProgressRequest, opts ...grpc.CallOption) (*UserQuest, error) {
	out := new(UserQuest)
	err := c.cc.Invoke(ctx, QuestsService_IncrementTaskProgress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questsServiceClient) UpdateTaskMetadata(ctx context.Context, in *UpdateTaskMetadataRequest, opts ...grpc.CallOption) (*UserQuest, error) {
	out := new(UserQuest)
	err := c.cc.Invoke(ctx, QuestsService_UpdateTaskMetadata_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questsServiceClient) BatchIncrementTaskProgress(ctx context.Context, in *BatchIncrementTaskProgressRequest, opts ...grpc.CallOption) (*BatchIncrementTaskProgressResponse, error) {
	out := new(BatchIncrementTaskProgressResponse)
	err := c.cc.Invoke(ctx, QuestsService_BatchIncrementTaskProgress_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questsServiceClient) EnableQuest(ctx context.Context, in *EnableQuestRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, QuestsService_EnableQuest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questsServiceClient) DisableQuest(ctx context.Context, in *DisableQuestRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, QuestsService_DisableQuest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questsServiceClient) UpdateProgressCallback(ctx context.Context, in *CallbackRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, QuestsService_UpdateProgressCallback_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questsServiceClient) ClaimQuestRewards(ctx context.Context, in *ClaimQuestRewardsRequest, opts ...grpc.CallOption) (*ClaimQuestRewardsResponse, error) {
	out := new(ClaimQuestRewardsResponse)
	err := c.cc.Invoke(ctx, QuestsService_ClaimQuestRewards_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questsServiceClient) ClaimTaskRewards(ctx context.Context, in *ClaimTaskRewardsRequest, opts ...grpc.CallOption) (*ClaimTaskRewardsResponse, error) {
	out := new(ClaimTaskRewardsResponse)
	err := c.cc.Invoke(ctx, QuestsService_ClaimTaskRewards_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questsServiceClient) BatchClaimQuestRewards(ctx context.Context, in *BatchClaimQuestRewardsRequest, opts ...grpc.CallOption) (*BatchClaimQuestRewardsResponse, error) {
	out := new(BatchClaimQuestRewardsResponse)
	err := c.cc.Invoke(ctx, QuestsService_BatchClaimQuestRewards_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questsServiceClient) BatchClaimTaskRewards(ctx context.Context, in *BatchClaimTaskRewardsRequest, opts ...grpc.CallOption) (*BatchClaimTaskRewardsResponse, error) {
	out := new(BatchClaimTaskRewardsResponse)
	err := c.cc.Invoke(ctx, QuestsService_BatchClaimTaskRewards_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questsServiceClient) GetUserData(ctx context.Context, in *UserDataRequest, opts ...grpc.CallOption) (*UserQuests, error) {
	out := new(UserQuests)
	err := c.cc.Invoke(ctx, QuestsService_GetUserData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questsServiceClient) DeleteUserData(ctx context.Context, in *UserDataRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, QuestsService_DeleteUserData_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questsServiceClient) ExportSettings(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*SettingsImportExportData, error) {
	out := new(SettingsImportExportData)
	err := c.cc.Invoke(ctx, QuestsService_ExportSettings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questsServiceClient) ImportSettings(ctx context.Context, in *SettingsImportExportData, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, QuestsService_ImportSettings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *questsServiceClient) ValidateImportSettings(ctx context.Context, in *SettingsImportExportData, opts ...grpc.CallOption) (*SettingsImportExportData, error) {
	out := new(SettingsImportExportData)
	err := c.cc.Invoke(ctx, QuestsService_ValidateImportSettings_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuestsServiceServer is the server API for QuestsService service.
// All implementations must embed UnimplementedQuestsServiceServer
// for forward compatibility
type QuestsServiceServer interface {
	// create a quest
	CreateQuest(context.Context, *CreateQuestRequest) (*Quest, error)
	// get all quests
	GetQuests(context.Context, *GetQuestsRequest) (*GetQuestsResponse, error)
	// get a quest by name
	GetQuest(context.Context, *GetQuestRequest) (*Quest, error)
	// delete a quest
	DeleteQuest(context.Context, *DeleteQuestRequest) (*emptypb.Empty, error)
	UpdateQuest(context.Context, *UpdateQuestRequest) (*Quest, error)
	// add task to a quest
	AddTaskToQuest(context.Context, *AddTaskToQuestRequest) (*Task, error)
	// delete a task from a quest
	RemoveTaskFromQuest(context.Context, *RemoveTaskRequest) (*emptypb.Empty, error)
	// get available quests for user
	GetAvailableQuests(context.Context, *GetAvailableQuestsRequest) (*GetAvailableQuestsResponse, error)
	// get active quests for user
	GetActiveQuests(context.Context, *GetActiveQuestsRequest) (*UserQuests, error)
	// BatchGetActiveQuests
	BatchGetActiveQuests(context.Context, *BatchGetActiveQuestsRequest) (*BatchGetActiveQuestsResponse, error)
	// assign a quest to a user
	AssignQuest(context.Context, *AssignQuestRequest) (*UserQuest, error)
	// delete user quest
	DeleteUserQuest(context.Context, *DeleteUserQuestRequest) (*emptypb.Empty, error)
	// update progress of a task in a quest for a user
	IncrementTaskProgress(context.Context, *IncrementTaskProgressRequest) (*UserQuest, error)
	// Update user metadata to a task in a quest assigned to a user
	UpdateTaskMetadata(context.Context, *UpdateTaskMetadataRequest) (*UserQuest, error)
	// BatchIncrementTaskProgress
	BatchIncrementTaskProgress(context.Context, *BatchIncrementTaskProgressRequest) (*BatchIncrementTaskProgressResponse, error)
	// enable quest
	EnableQuest(context.Context, *EnableQuestRequest) (*emptypb.Empty, error)
	// disable quest
	DisableQuest(context.Context, *DisableQuestRequest) (*emptypb.Empty, error)
	UpdateProgressCallback(context.Context, *CallbackRequest) (*emptypb.Empty, error)
	ClaimQuestRewards(context.Context, *ClaimQuestRewardsRequest) (*ClaimQuestRewardsResponse, error)
	ClaimTaskRewards(context.Context, *ClaimTaskRewardsRequest) (*ClaimTaskRewardsResponse, error)
	BatchClaimQuestRewards(context.Context, *BatchClaimQuestRewardsRequest) (*BatchClaimQuestRewardsResponse, error)
	BatchClaimTaskRewards(context.Context, *BatchClaimTaskRewardsRequest) (*BatchClaimTaskRewardsResponse, error)
	GetUserData(context.Context, *UserDataRequest) (*UserQuests, error)
	DeleteUserData(context.Context, *UserDataRequest) (*emptypb.Empty, error)
	ExportSettings(context.Context, *emptypb.Empty) (*SettingsImportExportData, error)
	ImportSettings(context.Context, *SettingsImportExportData) (*emptypb.Empty, error)
	ValidateImportSettings(context.Context, *SettingsImportExportData) (*SettingsImportExportData, error)
	mustEmbedUnimplementedQuestsServiceServer()
}

// UnimplementedQuestsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedQuestsServiceServer struct {
}

func (UnimplementedQuestsServiceServer) CreateQuest(context.Context, *CreateQuestRequest) (*Quest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateQuest not implemented")
}
func (UnimplementedQuestsServiceServer) GetQuests(context.Context, *GetQuestsRequest) (*GetQuestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuests not implemented")
}
func (UnimplementedQuestsServiceServer) GetQuest(context.Context, *GetQuestRequest) (*Quest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetQuest not implemented")
}
func (UnimplementedQuestsServiceServer) DeleteQuest(context.Context, *DeleteQuestRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteQuest not implemented")
}
func (UnimplementedQuestsServiceServer) UpdateQuest(context.Context, *UpdateQuestRequest) (*Quest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateQuest not implemented")
}
func (UnimplementedQuestsServiceServer) AddTaskToQuest(context.Context, *AddTaskToQuestRequest) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTaskToQuest not implemented")
}
func (UnimplementedQuestsServiceServer) RemoveTaskFromQuest(context.Context, *RemoveTaskRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveTaskFromQuest not implemented")
}
func (UnimplementedQuestsServiceServer) GetAvailableQuests(context.Context, *GetAvailableQuestsRequest) (*GetAvailableQuestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvailableQuests not implemented")
}
func (UnimplementedQuestsServiceServer) GetActiveQuests(context.Context, *GetActiveQuestsRequest) (*UserQuests, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActiveQuests not implemented")
}
func (UnimplementedQuestsServiceServer) BatchGetActiveQuests(context.Context, *BatchGetActiveQuestsRequest) (*BatchGetActiveQuestsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchGetActiveQuests not implemented")
}
func (UnimplementedQuestsServiceServer) AssignQuest(context.Context, *AssignQuestRequest) (*UserQuest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignQuest not implemented")
}
func (UnimplementedQuestsServiceServer) DeleteUserQuest(context.Context, *DeleteUserQuestRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserQuest not implemented")
}
func (UnimplementedQuestsServiceServer) IncrementTaskProgress(context.Context, *IncrementTaskProgressRequest) (*UserQuest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncrementTaskProgress not implemented")
}
func (UnimplementedQuestsServiceServer) UpdateTaskMetadata(context.Context, *UpdateTaskMetadataRequest) (*UserQuest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTaskMetadata not implemented")
}
func (UnimplementedQuestsServiceServer) BatchIncrementTaskProgress(context.Context, *BatchIncrementTaskProgressRequest) (*BatchIncrementTaskProgressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchIncrementTaskProgress not implemented")
}
func (UnimplementedQuestsServiceServer) EnableQuest(context.Context, *EnableQuestRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableQuest not implemented")
}
func (UnimplementedQuestsServiceServer) DisableQuest(context.Context, *DisableQuestRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableQuest not implemented")
}
func (UnimplementedQuestsServiceServer) UpdateProgressCallback(context.Context, *CallbackRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProgressCallback not implemented")
}
func (UnimplementedQuestsServiceServer) ClaimQuestRewards(context.Context, *ClaimQuestRewardsRequest) (*ClaimQuestRewardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimQuestRewards not implemented")
}
func (UnimplementedQuestsServiceServer) ClaimTaskRewards(context.Context, *ClaimTaskRewardsRequest) (*ClaimTaskRewardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimTaskRewards not implemented")
}
func (UnimplementedQuestsServiceServer) BatchClaimQuestRewards(context.Context, *BatchClaimQuestRewardsRequest) (*BatchClaimQuestRewardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchClaimQuestRewards not implemented")
}
func (UnimplementedQuestsServiceServer) BatchClaimTaskRewards(context.Context, *BatchClaimTaskRewardsRequest) (*BatchClaimTaskRewardsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchClaimTaskRewards not implemented")
}
func (UnimplementedQuestsServiceServer) GetUserData(context.Context, *UserDataRequest) (*UserQuests, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserData not implemented")
}
func (UnimplementedQuestsServiceServer) DeleteUserData(context.Context, *UserDataRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserData not implemented")
}
func (UnimplementedQuestsServiceServer) ExportSettings(context.Context, *emptypb.Empty) (*SettingsImportExportData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportSettings not implemented")
}
func (UnimplementedQuestsServiceServer) ImportSettings(context.Context, *SettingsImportExportData) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportSettings not implemented")
}
func (UnimplementedQuestsServiceServer) ValidateImportSettings(context.Context, *SettingsImportExportData) (*SettingsImportExportData, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateImportSettings not implemented")
}
func (UnimplementedQuestsServiceServer) mustEmbedUnimplementedQuestsServiceServer() {}

// UnsafeQuestsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuestsServiceServer will
// result in compilation errors.
type UnsafeQuestsServiceServer interface {
	mustEmbedUnimplementedQuestsServiceServer()
}

func RegisterQuestsServiceServer(s grpc.ServiceRegistrar, srv QuestsServiceServer) {
	s.RegisterService(&QuestsService_ServiceDesc, srv)
}

func _QuestsService_CreateQuest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateQuestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestsServiceServer).CreateQuest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestsService_CreateQuest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestsServiceServer).CreateQuest(ctx, req.(*CreateQuestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestsService_GetQuests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestsServiceServer).GetQuests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestsService_GetQuests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestsServiceServer).GetQuests(ctx, req.(*GetQuestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestsService_GetQuest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQuestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestsServiceServer).GetQuest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestsService_GetQuest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestsServiceServer).GetQuest(ctx, req.(*GetQuestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestsService_DeleteQuest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteQuestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestsServiceServer).DeleteQuest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestsService_DeleteQuest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestsServiceServer).DeleteQuest(ctx, req.(*DeleteQuestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestsService_UpdateQuest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateQuestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestsServiceServer).UpdateQuest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestsService_UpdateQuest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestsServiceServer).UpdateQuest(ctx, req.(*UpdateQuestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestsService_AddTaskToQuest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddTaskToQuestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestsServiceServer).AddTaskToQuest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestsService_AddTaskToQuest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestsServiceServer).AddTaskToQuest(ctx, req.(*AddTaskToQuestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestsService_RemoveTaskFromQuest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestsServiceServer).RemoveTaskFromQuest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestsService_RemoveTaskFromQuest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestsServiceServer).RemoveTaskFromQuest(ctx, req.(*RemoveTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestsService_GetAvailableQuests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailableQuestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestsServiceServer).GetAvailableQuests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestsService_GetAvailableQuests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestsServiceServer).GetAvailableQuests(ctx, req.(*GetAvailableQuestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestsService_GetActiveQuests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveQuestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestsServiceServer).GetActiveQuests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestsService_GetActiveQuests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestsServiceServer).GetActiveQuests(ctx, req.(*GetActiveQuestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestsService_BatchGetActiveQuests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchGetActiveQuestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestsServiceServer).BatchGetActiveQuests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestsService_BatchGetActiveQuests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestsServiceServer).BatchGetActiveQuests(ctx, req.(*BatchGetActiveQuestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestsService_AssignQuest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignQuestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestsServiceServer).AssignQuest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestsService_AssignQuest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestsServiceServer).AssignQuest(ctx, req.(*AssignQuestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestsService_DeleteUserQuest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserQuestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestsServiceServer).DeleteUserQuest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestsService_DeleteUserQuest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestsServiceServer).DeleteUserQuest(ctx, req.(*DeleteUserQuestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestsService_IncrementTaskProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrementTaskProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestsServiceServer).IncrementTaskProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestsService_IncrementTaskProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestsServiceServer).IncrementTaskProgress(ctx, req.(*IncrementTaskProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestsService_UpdateTaskMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTaskMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestsServiceServer).UpdateTaskMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestsService_UpdateTaskMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestsServiceServer).UpdateTaskMetadata(ctx, req.(*UpdateTaskMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestsService_BatchIncrementTaskProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchIncrementTaskProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestsServiceServer).BatchIncrementTaskProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestsService_BatchIncrementTaskProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestsServiceServer).BatchIncrementTaskProgress(ctx, req.(*BatchIncrementTaskProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestsService_EnableQuest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableQuestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestsServiceServer).EnableQuest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestsService_EnableQuest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestsServiceServer).EnableQuest(ctx, req.(*EnableQuestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestsService_DisableQuest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableQuestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestsServiceServer).DisableQuest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestsService_DisableQuest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestsServiceServer).DisableQuest(ctx, req.(*DisableQuestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestsService_UpdateProgressCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestsServiceServer).UpdateProgressCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestsService_UpdateProgressCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestsServiceServer).UpdateProgressCallback(ctx, req.(*CallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestsService_ClaimQuestRewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimQuestRewardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestsServiceServer).ClaimQuestRewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestsService_ClaimQuestRewards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestsServiceServer).ClaimQuestRewards(ctx, req.(*ClaimQuestRewardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestsService_ClaimTaskRewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimTaskRewardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestsServiceServer).ClaimTaskRewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestsService_ClaimTaskRewards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestsServiceServer).ClaimTaskRewards(ctx, req.(*ClaimTaskRewardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestsService_BatchClaimQuestRewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchClaimQuestRewardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestsServiceServer).BatchClaimQuestRewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestsService_BatchClaimQuestRewards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestsServiceServer).BatchClaimQuestRewards(ctx, req.(*BatchClaimQuestRewardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestsService_BatchClaimTaskRewards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchClaimTaskRewardsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestsServiceServer).BatchClaimTaskRewards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestsService_BatchClaimTaskRewards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestsServiceServer).BatchClaimTaskRewards(ctx, req.(*BatchClaimTaskRewardsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestsService_GetUserData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestsServiceServer).GetUserData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestsService_GetUserData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestsServiceServer).GetUserData(ctx, req.(*UserDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestsService_DeleteUserData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestsServiceServer).DeleteUserData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestsService_DeleteUserData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestsServiceServer).DeleteUserData(ctx, req.(*UserDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestsService_ExportSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestsServiceServer).ExportSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestsService_ExportSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestsServiceServer).ExportSettings(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestsService_ImportSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsImportExportData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestsServiceServer).ImportSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestsService_ImportSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestsServiceServer).ImportSettings(ctx, req.(*SettingsImportExportData))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuestsService_ValidateImportSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsImportExportData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuestsServiceServer).ValidateImportSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuestsService_ValidateImportSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuestsServiceServer).ValidateImportSettings(ctx, req.(*SettingsImportExportData))
	}
	return interceptor(ctx, in, info, handler)
}

// QuestsService_ServiceDesc is the grpc.ServiceDesc for QuestsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuestsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "quests.QuestsService",
	HandlerType: (*QuestsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateQuest",
			Handler:    _QuestsService_CreateQuest_Handler,
		},
		{
			MethodName: "GetQuests",
			Handler:    _QuestsService_GetQuests_Handler,
		},
		{
			MethodName: "GetQuest",
			Handler:    _QuestsService_GetQuest_Handler,
		},
		{
			MethodName: "DeleteQuest",
			Handler:    _QuestsService_DeleteQuest_Handler,
		},
		{
			MethodName: "UpdateQuest",
			Handler:    _QuestsService_UpdateQuest_Handler,
		},
		{
			MethodName: "AddTaskToQuest",
			Handler:    _QuestsService_AddTaskToQuest_Handler,
		},
		{
			MethodName: "RemoveTaskFromQuest",
			Handler:    _QuestsService_RemoveTaskFromQuest_Handler,
		},
		{
			MethodName: "GetAvailableQuests",
			Handler:    _QuestsService_GetAvailableQuests_Handler,
		},
		{
			MethodName: "GetActiveQuests",
			Handler:    _QuestsService_GetActiveQuests_Handler,
		},
		{
			MethodName: "BatchGetActiveQuests",
			Handler:    _QuestsService_BatchGetActiveQuests_Handler,
		},
		{
			MethodName: "AssignQuest",
			Handler:    _QuestsService_AssignQuest_Handler,
		},
		{
			MethodName: "DeleteUserQuest",
			Handler:    _QuestsService_DeleteUserQuest_Handler,
		},
		{
			MethodName: "IncrementTaskProgress",
			Handler:    _QuestsService_IncrementTaskProgress_Handler,
		},
		{
			MethodName: "UpdateTaskMetadata",
			Handler:    _QuestsService_UpdateTaskMetadata_Handler,
		},
		{
			MethodName: "BatchIncrementTaskProgress",
			Handler:    _QuestsService_BatchIncrementTaskProgress_Handler,
		},
		{
			MethodName: "EnableQuest",
			Handler:    _QuestsService_EnableQuest_Handler,
		},
		{
			MethodName: "DisableQuest",
			Handler:    _QuestsService_DisableQuest_Handler,
		},
		{
			MethodName: "UpdateProgressCallback",
			Handler:    _QuestsService_UpdateProgressCallback_Handler,
		},
		{
			MethodName: "ClaimQuestRewards",
			Handler:    _QuestsService_ClaimQuestRewards_Handler,
		},
		{
			MethodName: "ClaimTaskRewards",
			Handler:    _QuestsService_ClaimTaskRewards_Handler,
		},
		{
			MethodName: "BatchClaimQuestRewards",
			Handler:    _QuestsService_BatchClaimQuestRewards_Handler,
		},
		{
			MethodName: "BatchClaimTaskRewards",
			Handler:    _QuestsService_BatchClaimTaskRewards_Handler,
		},
		{
			MethodName: "GetUserData",
			Handler:    _QuestsService_GetUserData_Handler,
		},
		{
			MethodName: "DeleteUserData",
			Handler:    _QuestsService_DeleteUserData_Handler,
		},
		{
			MethodName: "ExportSettings",
			Handler:    _QuestsService_ExportSettings_Handler,
		},
		{
			MethodName: "ImportSettings",
			Handler:    _QuestsService_ImportSettings_Handler,
		},
		{
			MethodName: "ValidateImportSettings",
			Handler:    _QuestsService_ValidateImportSettings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "quests_services.proto",
}
